import test from 'node:test';import assert from 'node:assert/strict';
import {AdaptiveResolution} from '../client/src/game/Performance';
import {SnapshotEncoder,SnapshotDecoder} from '../shared/snapshots';
import {Simulation,seatPosition} from '../server/src/simulation';
import {NullEngine,Scene,MeshBuilder} from '@babylonjs/core';
import {ChunkVisibility} from '../client/src/game/Chunks';
test('riders use bus anchors without repeated world positions, detach restores walking',()=>{const sim=new Simulation();const p=sim.join('r','Rider');const b=sim.state.buses[0];p.busId=b.id;p.role='passenger';p.seat=0;b.passengers=[p.id];const enc=new SnapshotEncoder(),dec=new SnapshotDecoder();dec.reset(sim.snapshot());dec.decode(enc.encode(sim.snapshot()));b.x+=10;b.yaw=.7;Object.assign(p,seatPosition(b,0));const packet=enc.encode(sim.snapshot());assert.ok(packet.players.every(v=>v.x===undefined&&v.z===undefined));const out=dec.decode(packet).players[0];assert.ok(Math.abs(out.x-seatPosition(b,0).x)<.01);p.role='walker';p.busId=null;p.x=99;p.z=22;const detached=dec.decode(enc.encode(sim.snapshot())).players[0];assert.equal(detached.x,99);assert.equal(detached.busId,null);});
test('adaptive resolution waits for sustained performance and stays bounded',()=>{const a=new AdaptiveResolution();let scale=1.2;for(let i=0;i<100;i++)scale=a.sample(.05,scale);assert.equal(scale,1.2);for(let i=0;i<70;i++)scale=a.sample(.05,scale);assert.ok(Math.abs(scale-1.35)<1e-8);for(let i=0;i<5000;i++)scale=a.sample(.1,scale);assert.equal(scale,2.5);});
test('chunks deactivate distant scenery and restore it when the player returns',()=>{const engine=new NullEngine();const scene=new Scene(engine),chunks=new ChunkVisibility();const a=MeshBuilder.CreateBox('near',{},scene),b=MeshBuilder.CreateBox('far',{},scene);b.position.x=1000;chunks.add(a);chunks.add(b);chunks.update(1,0,0,230);assert.ok(a.isEnabled());assert.equal(b.isEnabled(),false);chunks.update(1,1000,0,230);assert.ok(b.isEnabled());assert.equal(a.isEnabled(),false);scene.dispose();engine.dispose();});
