import {RoadSignals} from './RoadSignals';
import {PRESETS} from './Performance';
import {Scene} from '@babylonjs/core/scene.js';
import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder.js';
import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial.js';
import {Color3} from '@babylonjs/core/Maths/math.color.js';
import {TransformNode} from '@babylonjs/core/Meshes/transformNode.js';
import {Mesh} from '@babylonjs/core/Meshes/mesh.js';
import {Vector3} from '@babylonjs/core/Maths/math.vector.js';
import {ParticleSystem} from '@babylonjs/core/Particles/particleSystem.js';
import {DynamicTexture} from '@babylonjs/core/Materials/Textures/dynamicTexture.js';
import {DISCOVERIES,STOPS} from '../../../shared/game-data';
import type {PlayerState,Weather} from '../../../shared/types';import type {TrafficState} from '../../../shared/traffic';
export class Activities {
 private signals:RoadSignals;
 private markers=new Map<string,Mesh>();private traffic=new Map<string,TransformNode>();private rain:ParticleSystem;private clock=0;private current='';private preset=PRESETS.medium;private emitter=new Vector3();
 constructor(private scene:Scene){this.signals=new RoadSignals(scene);
  const mat=(n:string,c:string)=>{const m=new StandardMaterial(n,scene);m.diffuseColor=Color3.FromHexString(c);m.specularColor=Color3.Black();m.freeze();return m;};const gold=mat('discovery','#e8bd69');gold.unfreeze();gold.emissiveColor=Color3.FromHexString('#735b20');gold.freeze();const blue=mat('stops','#529689');
  const stops:Mesh[]=[];for(const s of STOPS.filter(s=>s.x<1500)){const pole=MeshBuilder.CreateCylinder('stop '+s.id,{height:3.5,diameter:.13,tessellation:6},scene);pole.position.set(s.x,1.75,s.z+7);pole.material=blue;stops.push(pole);const ring=MeshBuilder.CreateTorus('stop zone',{diameter:s.radius*1.7,thickness:.12,tessellation:24},scene);ring.position.set(s.x,.16,s.z);ring.material=blue;stops.push(ring);}const stopMesh=Mesh.MergeMeshes(stops,true,true,undefined,false,false);stopMesh?.freezeWorldMatrix();if(stopMesh)stopMesh.isPickable=false;
  for(const item of DISCOVERIES){const marker=MeshBuilder.CreatePolyhedron(item.id,{type:1,size:item.action==='collect'?.2:.45},scene);marker.position.set(item.x,item.action==='collect'?.3:2,item.z);marker.material=gold;marker.isPickable=false;this.markers.set(item.id,marker);if(item.category==='Plants'){const trunk=MeshBuilder.CreateCylinder(item.name,{height:3,diameter:.25,tessellation:6},scene);trunk.position.set(item.x,1.5,item.z);trunk.material=mat(item.id+' trunk','#8c7753');const leaves=mat(item.id+' leaves','#517846');if(item.id==='plant-1'){for(let i=0;i<5;i++){const leaf=MeshBuilder.CreateSphere('banana leaf',{diameter:1,segments:4},scene);leaf.scaling.set(.45,.1,2);leaf.position.set(item.x+Math.sin(i)*.6,3.1,item.z+Math.cos(i)*.6);leaf.rotation.y=i*1.25;leaf.material=leaves;}}else{const crown=MeshBuilder.CreateSphere(item.name,{diameter:3,segments:6},scene);crown.position.set(item.x,3.8,item.z);crown.material=leaves;}}}
  this.rain=new ParticleSystem('monsoon',220,scene);const t=new DynamicTexture('rain drop',16,scene,false);const ctx=t.getContext();ctx.clearRect(0,0,16,16);ctx.fillStyle='white';ctx.fillRect(7,0,2,16);t.hasAlpha=true;t.update();this.rain.particleTexture=t;this.rain.minEmitBox=new Vector3(-15,12,-15);this.rain.maxEmitBox=new Vector3(15,17,15);this.rain.direction1=new Vector3(-1,-20,0);this.rain.direction2=new Vector3(-2,-25,0);this.rain.minLifeTime=.7;this.rain.maxLifeTime=1;this.rain.emitRate=160;this.rain.minSize=.1;this.rain.maxSize=.2;
 }
 private vehicle(t:TrafficState){const root=new TransformNode(t.id,this.scene);const material=new StandardMaterial(t.id,this.scene);material.diffuseColor=Color3.FromHexString({car:'#a9bdac',auto:'#c8ad3d',bike:'#934f3d',truck:'#668e85'}[t.kind]);material.specularColor=Color3.Black();material.freeze();const black=new StandardMaterial(t.id+' dark',this.scene);black.diffuseColor=Color3.FromHexString('#294441');black.freeze();const pieces:Mesh[]=[];const box=(x:number,y:number,z:number,w:number,h:number,d:number)=>{const m=MeshBuilder.CreateBox(t.kind,{width:w,height:h,depth:d},this.scene);m.position.set(x,y,z);m.material=material;pieces.push(m);};const bike=t.kind==='bike',truck=t.kind==='truck',auto=t.kind==='auto';box(0,.7,0,bike?.55:auto?1.25:1.65,.65,bike?1.9:truck?4.6:3.2);box(0,1.35,truck?1.25:0,bike?.45:1.15,.7,truck?1.4:auto?1.8:1.5);if(truck)box(0,1.4,-.8,1.7,1.25,2.6);const merged=Mesh.MergeMeshes(pieces,true,true,undefined,false,false)!;merged.parent=root;merged.isPickable=false;for(const z of [-.85,.85]){const axle=MeshBuilder.CreateCylinder('traffic wheels',{diameter:.55,height:bike?.25:1.7,tessellation:8},this.scene);axle.parent=root;axle.rotation.z=Math.PI/2;axle.position.set(0,.36,z);axle.material=black;axle.isPickable=false;}this.traffic.set(t.id,root);return root;}
 quality(preset:typeof PRESETS.medium){this.preset=preset;}
 update(dt:number,p:PlayerState|null,traffic:TrafficState[]=[],serverNow=Date.now()){this.signals.update(p?.x||0,serverNow);this.clock+=dt;for(const item of DISCOVERIES){const marker=this.markers.get(item.id)!;const near=!p||Math.hypot(item.x-p.x,item.z-p.z)<this.preset.markers;marker.setEnabled(near&&!p?.progress.journal.includes(item.id));if(near){marker.rotation.y+=dt;if(item.action!=='collect')marker.position.y=2+Math.sin(this.clock*2+item.x)*.15;}}
  const ids=new Set(traffic.map(t=>t.id));
  for(const [id,root] of this.traffic){const t=traffic.find(t=>t.id===id);if(!ids.has(id)||(p&&t&&Math.hypot(t.x-p.x,t.z-p.z)>this.preset.traffic+60)){root.dispose(false,true);this.traffic.delete(id);}}
  for(const t of traffic){const distance=p?Math.hypot(t.x-p.x,t.z-p.z):Infinity;let root=this.traffic.get(t.id);if(!root&&distance<this.preset.traffic){root=this.vehicle(t);root.position.set(t.x,0,t.z);root.rotation.y=t.yaw;}if(!root)continue;root.setEnabled(distance<this.preset.traffic+20);const weight=1-Math.exp(-dt*14);if(Math.hypot(t.x-root.position.x,t.z-root.position.z)>30){root.position.x=t.x;root.position.z=t.z;}else{root.position.x+=(t.x-root.position.x)*weight;root.position.z+=(t.z-root.position.z)*weight;}root.rotation.y+=Math.atan2(Math.sin(t.yaw-root.rotation.y),Math.cos(t.yaw-root.rotation.y))*weight;}
  if(p)this.emitter.set(p.x,0,p.z);this.rain.emitter=this.emitter;this.rain.emitRate=p?this.preset.rain*(this.current==='light-rain'?.45:this.current==='heavy-rain'?1.3:1):0;
  const fog=this.current==='fog'?.013:this.current==='mist'?.009:['rain','heavy-rain'].includes(this.current)?.007:this.current==='cloudy'?.004:.0024;this.scene.fogDensity+=(fog-this.scene.fogDensity)*(1-Math.exp(-dt*1.5));

 }
 weather(value:Weather){if(this.current===value)return;this.current=value;['rain','light-rain','heavy-rain'].includes(value)?this.rain.start():this.rain.stop();}
}
