import {Scene,TransformNode,MeshBuilder,StandardMaterial,Color3,DynamicTexture,SpotLight,Vector3,Mesh} from '@babylonjs/core';
import type {BusState} from '../../../shared/types';
export class BusModel {
 root:TransformNode;private door:TransformNode;private wheels:Mesh[]=[];private lamps:SpotLight[]=[];private display:DynamicTexture;private route='';private roll=0;
 constructor(scene:Scene,b:BusState,color:string){
  this.root=new TransformNode(b.id,scene);const mat=(name:string,hex:string,alpha=1)=>{const m=new StandardMaterial(name,scene);m.diffuseColor=Color3.FromHexString(hex);m.specularColor=new Color3(.16,.16,.16);m.alpha=alpha;return m;};
  const body=mat('bus paint '+b.id,color),cream=mat('ivory '+b.id,'#efe2bb'),black=mat('tyres '+b.id,'#202d2d'),glass=mat('glass '+b.id,'#83b3b5',.32),metal=mat('trim '+b.id,'#abbab4'),seat=mat('seats '+b.id,'#496c65');glass.backFaceCulling=false;
  const box=(name:string,x:number,y:number,z:number,w:number,h:number,d:number,m:StandardMaterial,parent=this.root)=>{const mesh=MeshBuilder.CreateBox(name,{width:w,height:h,depth:d},scene);mesh.position.set(x,y,z);mesh.parent=parent;mesh.material=m;mesh.receiveShadows=true;return mesh;};
  box('chassis',0,.55,0,2.8,.38,9.7,black);box('floor',0,.95,0,2.85,.22,9.75,cream);box('roof',0,3.65,0,2.95,.22,9.9,cream);box('right body',1.4,1.5,0,.16,1.05,9.7,body);box('left body',-1.4,1.5,-1,.16,1.05,7.7,body);
  for(const side of [-1,1]){for(let z=-4.2;z<4.6;z+=1.25){if(side<0&&z>2)continue;box('window pillar',side*1.42,2.83,z,.12,1.45,.11,cream);box('side window',side*1.42,2.78,z+.59,.06,1.15,1.08,glass);}box('waist stripe',side*1.49,1.83,side<0?-1:0,.035,.2,side<0?7.6:9.6,cream);}
  box('front',0,1.55,4.8,2.9,1.3,.16,body);box('windscreen',0,2.65,4.82,2.66,1.2,.07,glass);box('windshield centre',0,2.7,4.88,.06,1.3,.06,cream);box('rear',0,2,-4.82,2.9,2.95,.14,body);box('rear glass',0,2.8,-4.91,2.3,1.1,.07,glass);
  box('bumper',0,.92,4.97,3,.25,.22,metal);box('grille',0,1.45,4.91,1.35,.38,.05,black);for(let i=0;i<4;i++)box('grille slat',0,1.3+i*.09,4.96,1.3,.025,.02,metal);
  const glow=mat('headlamp '+b.id,'#fff1b9');glow.emissiveColor=Color3.FromHexString('#b3a36e');for(const x of [-1.08,1.08]){box('headlight',x,1.35,4.93,.45,.3,.06,glow);box('mirror stalk',x*1.52,2.95,4.7,.35,.07,.08,metal);box('mirror',x*1.66,2.75,4.72,.1,.42,.22,black);const lamp=new SpotLight('beam',new Vector3(x,1.4,5),new Vector3(0,-.05,1),Math.PI/3,2,scene);lamp.parent=this.root;lamp.intensity=0;lamp.range=40;this.lamps.push(lamp);}
  for(const x of [-1.45,1.45])for(const z of [-3.15,3.1]){const wheel=MeshBuilder.CreateCylinder('wheel',{height:.32,diameter:1.23,tessellation:16},scene);wheel.parent=this.root;wheel.position.set(x,.63,z);wheel.rotation.z=Math.PI/2;wheel.material=black;const hub=MeshBuilder.CreateCylinder('hub',{height:.34,diameter:.6,tessellation:12},scene);hub.parent=wheel;hub.material=metal;this.wheels.push(wheel);}
  for(let i=0;i<10;i++){const x=i%2?.77:-.77,z=2.4-Math.floor(i/2)*1.15;box('seat cushion',x,1.37,z,.6,.16,.64,seat);box('seat back',x,1.79,z-.28,.65,.8,.15,seat);}
  box('driver cushion',.75,1.43,3.75,.65,.18,.65,seat);box('dashboard',.45,1.96,4.35,1.8,.35,.5,black);
  const steering=MeshBuilder.CreateTorus('steering wheel',{diameter:.53,thickness:.055,tessellation:16},scene);steering.parent=this.root;steering.position.set(.8,2.02,3.98);steering.rotation.x=-.5;steering.material=black;
  this.door=new TransformNode('left folding door',scene);this.door.parent=this.root;this.door.position.set(-1.46,1,3.15);box('door panel',0,1.23,0,.12,2.42,1.6,glass,this.door);box('door frame',0,1.25,-.8,.16,2.5,.08,cream,this.door);box('step',-1.6,.7,3.15,.6,.17,1.7,metal);
  this.display=new DynamicTexture('destination '+b.id,{width:512,height:96},scene,false);const label=mat('route board '+b.id,'#ffffff');label.diffuseTexture=this.display;label.emissiveColor=new Color3(.35,.35,.25);box('destination box',0,3.36,4.88,2.6,.42,.1,black);const plane=MeshBuilder.CreatePlane('destination text',{width:2.48,height:.4},scene);plane.parent=this.root;plane.position.set(0,3.36,4.95);plane.rotation.y=Math.PI;plane.material=label;
  const groups=new Map<number,Mesh[]>();
  for(const child of this.root.getChildMeshes(true)){const m=child as Mesh;if(this.wheels.includes(m))continue;if(!m.material)continue;const group=groups.get(m.material.uniqueId)||[];group.push(m);groups.set(m.material.uniqueId,group);}
  for(const list of groups.values()){const m=Mesh.MergeMeshes(list,true,true,undefined,false,false);if(m){m.parent=this.root;m.isPickable=false;m.receiveShadows=true;}}

 }
 update(b:BusState,dt:number,smooth=1){this.root.position.x+=(b.x-this.root.position.x)*smooth;this.root.position.z+=(b.z-this.root.position.z)*smooth;this.root.rotation.y+=Math.atan2(Math.sin(b.yaw-this.root.rotation.y),Math.cos(b.yaw-this.root.rotation.y))*smooth;this.door.rotation.y+=( (b.doors?-1.35:0)-this.door.rotation.y)*Math.min(1,dt*10);this.roll+=b.speed*dt/.615;for(const w of this.wheels)w.rotation.x=this.roll;this.lamps.forEach(l=>l.intensity=b.lights?2:0);if(this.route!==b.route+b.direction){this.route=b.route+b.direction;const c=this.display.getContext() as CanvasRenderingContext2D;c.fillStyle='#193b30';c.fillRect(0,0,512,96);c.fillStyle='#ffe2a0';c.font='bold 33px sans-serif';c.textAlign='center';c.fillText(b.direction===-1?b.route+'  ·  KSRTC TERMINAL':b.route==='A'?'A  ·  KOZHIKODE BEACH':'B  ·  NIT CALICUT',256,61);this.display.update();}}
 dispose(){this.root.dispose(false,true);this.display.dispose();this.lamps.forEach(l=>l.dispose());}
}
