import {seatPosition} from '../server/src/simulation';
import type {Snapshot,PlayerState,BusState} from './types';import type {TrafficState} from './traffic';
type Patch<T>={id:string}&Partial<T>;
export type Frame={npcs?:Patch<import("../server/src/npc").NpcPassenger>[];trafficGone?:string[];delta:true;time:number;players:Patch<PlayerState>[];buses:Patch<BusState>[];traffic:Patch<TrafficState>[];gone:string[];weather:Snapshot['weather'];events:Snapshot['events']};
function rounded<T extends {id:string}>(value:T):T{const result={...value} as any;for(const key of ['x','z','yaw','speed','steer'])if(typeof result[key]==='number')result[key]=Math.round(result[key]*1000)/1000;return result;}
export class SnapshotEncoder {
 private previous=new Map<string,Record<string,unknown>>();private ids=new Set<string>();private trafficIds=new Set<string>();
 encode(s:Snapshot):Frame{const patch=<T extends {id:string}>(kind:string,values:T[])=>values.flatMap(value=>{const current=rounded(value);const cache=this.previous.get(kind+value.id)||{};const out:Record<string,unknown>={id:value.id};let changed=false;if(kind==='p'&&cache.role!==(current as any).role){delete cache.x;delete cache.z;delete cache.yaw;}for(const [key,v] of Object.entries(current)){if(kind==='p'&&(current as any).busId&&['x','z','yaw'].includes(key))continue;const json=v!==null&&typeof v==='object'?JSON.stringify(v):v;if(cache[key]!==json){out[key]=v;cache[key]=json;changed=true;}}this.previous.set(kind+value.id,cache);return changed?[out as Patch<T>]:[];});const currentIds=new Set(s.players.map(p=>p.id));const gone=[...this.ids].filter(id=>!currentIds.has(id));for(const id of gone)this.previous.delete('p'+id);this.ids=currentIds;const currentTraffic=new Set(s.traffic.map(t=>t.id)),trafficGone=[...this.trafficIds].filter(id=>!currentTraffic.has(id));for(const id of trafficGone)this.previous.delete('t'+id);this.trafficIds=currentTraffic;return {trafficGone,delta:true,time:s.time,players:patch('p',s.players),buses:patch('b',s.buses),traffic:patch('t',s.traffic),gone,npcs:patch('n',s.npcs||[]),weather:s.weather,events:s.events};}
}
export class SnapshotDecoder {
 private state:Snapshot={time:0,players:[],buses:[],traffic:[],weather:'clear',events:[]};
 reset(s:Snapshot){this.state=structuredClone(s);}
 decode(frame:Frame):Snapshot{const merge=<T extends {id:string}>(values:T[],patches:Patch<T>[])=>{const map=new Map(values.map(v=>[v.id,v]));for(const p of patches)map.set(p.id,{...map.get(p.id),...p} as T);return [...map.values()];};this.state={time:frame.time,players:merge(this.state.players.filter(p=>!frame.gone.includes(p.id)),frame.players),buses:merge(this.state.buses,frame.buses),traffic:merge(this.state.traffic.filter(t=>!frame.trafficGone?.includes(t.id)),frame.traffic),npcs:merge(this.state.npcs||[],frame.npcs||[]),weather:frame.weather,events:frame.events};for(const p of this.state.players){if(p.busId){const b=this.state.buses.find(b=>b.id===p.busId);if(b){Object.assign(p,seatPosition(b,p.standing?10+p.seat%2:p.seat,p.role==='driver'));p.yaw=b.yaw;}}}return structuredClone(this.state);}
}
