import assert from 'node:assert/strict';import {spawn,type ChildProcess} from 'node:child_process';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
import {io,type Socket} from 'socket.io-client';import {SnapshotDecoder} from '../shared/snapshots';import {seatPosition} from '../server/src/simulation';import type {Snapshot,Action} from '../shared/types';
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms)),port=3206,url='http://127.0.0.1:'+port,folder=await mkdtemp(path.join(tmpdir(),'kr-built-smoke-'));
const expectedVersion=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8')).version;
let server:ChildProcess|undefined;const sockets:Socket[]=[];
async function start(){server=spawn(process.execPath,['dist-server/index.js'],{env:{...process.env,PORT:String(port),NODE_ENV:'production',LOCAL_ONLY:'true',LOCAL_SAVE_DIR:folder,SUPABASE_URL:'https://invalid.example',SUPABASE_SECRET_KEY:'test-only-invalid',RECONNECT_GRACE_MS:'0'},stdio:'pipe'});let stderr='';server.stderr?.on('data',s=>stderr+=s);for(let i=0;i<80;i++){try{const response=await fetch(url+'/health');if(response.ok){const health=await response.json();assert.equal(health.version,expectedVersion);assert.equal(health.persistence,true);return;}}catch{}if(server.exitCode!==null)throw Error('Built server exited: '+stderr);await sleep(100);}throw Error('Built server timed out: '+stderr);}
async function stop(){if(!server||server.exitCode!==null)return;const child=server;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error('Shutdown timed out'));},10000);child.once('exit',()=>{clearTimeout(timer);resolve();});child.kill('SIGTERM');});}
async function join(index:number){const socket=io(url,{transports:['websocket'],reconnection:false}),decoder=new SnapshotDecoder();sockets.push(socket);let state:Snapshot;const welcome=await new Promise<any>((resolve,reject)=>{socket.on('connect_error',reject);socket.on('connect',()=>socket.emit('join',{name:'Built tester '+index,token:String(index).repeat(64)},(r:any)=>{if(!r.ok)return reject(Error(r.message));state={...r.welcome,events:[]};decoder.reset(state);resolve(r.welcome);}));socket.on('snapshot',frame=>{state=decoder.decode(frame);});});return {socket,id:welcome.id,get state(){return state;},seq:0};}
async function walk(client:Awaited<ReturnType<typeof join>>,x:number,z:number){for(let i=0;i<160;i++){const p=client.state.players.find(p=>p.id===client.id)!;const dx=x-p.x,dz=z-p.z,length=Math.hypot(dx,dz);if(length<.8){client.socket.emit('input',{seq:++client.seq,x:0,z:0,sprint:false});return;}client.socket.emit('input',{seq:++client.seq,x:dx/length,z:dz/length,sprint:true});await sleep(50);}throw Error('Could not walk to bus');}
async function act(client:Awaited<ReturnType<typeof join>>,action:Action){await sleep(180);const result=await new Promise<any>((resolve,reject)=>client.socket.timeout(6000).emit('action',action,(error:Error|null,r:any)=>error?reject(error):resolve(r)));assert.ok(result.ok,result.message);}
try{
 await start();const html=await(await fetch(url)).text();assert.ok(html.includes('<canvas'));const script=html.match(/src="([^"]+\.js)"/)?.[1];assert.ok(script);assert.ok((await fetch(new URL(script,url))).ok);
 const driver=await join(1),passenger=await join(2);await Promise.all([walk(driver,29,11),walk(passenger,29.2,14)]);
 await act(driver,{type:'claim',target:'bus-1'});await act(passenger,{type:'board',target:'bus-1'});await act(driver,{type:'door'});await act(driver,{type:'handbrake'});
 for(let i=0;i<22;i++){driver.socket.emit('input',{seq:++driver.seq,x:0,z:0,sprint:false,throttle:1,steer:0});await sleep(50);}assert.ok(driver.state.buses[0].speed>1);
 const rider=passenger.state.players.find(p=>p.id===passenger.id)!,bus=passenger.state.buses[0],seat=seatPosition(bus,rider.seat);assert.equal(rider.role,'passenger');assert.ok(Math.hypot(rider.x-seat.x,rider.z-seat.z)<.01);
 for(let i=0;i<15;i++){driver.socket.emit('input',{seq:++driver.seq,x:0,z:0,sprint:false,brake:true});await sleep(50);}await act(driver,{type:'door'});await act(passenger,{type:'exit'});await sleep(150);
 const before=passenger.state.players.find(p=>p.id===passenger.id)!.progress;assert.ok(before.kp>0);await stop();for(const socket of sockets)socket.disconnect();
 await start();const returning=await join(2),after=returning.state.players.find(p=>p.id===returning.id)!.progress;assert.deepEqual(after,before);
 console.log(JSON.stringify({compiledAssets:'served',server:expectedVersion,players:2,walking:'passed',driverOwnership:'passed',boarding:'passed',driving:'passed',passengerAnchoring:'passed',exit:'passed',restartPersistence:'passed',productionCredentials:'isolated',savedKP:after.kp},null,2));
}finally{for(const socket of sockets)socket.disconnect();await stop();await rm(folder,{recursive:true,force:true});}
